// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Pokemon struct {
	ID                 int     `json:"id"`
	Num                int     `json:"num"`
	Name               string  `json:"name"`
	Classification     string  `json:"classification"`
	Alternate          *string `json:"alternate"`
	Og                 *string `json:"og"`
	Legendary          *string `json:"legendary"`
	Height             float64 `json:"height"`
	Weight             float64 `json:"weight"`
	PrimType           string  `json:"primType"`
	SecType            *string `json:"secType"`
	PrimAbil           string  `json:"primAbil"`
	PrimAbilDesc       string  `json:"primAbilDesc"`
	SecAbil            *string `json:"secAbil"`
	SecAbilDesc        *string `json:"secAbilDesc"`
	HiddenAbil         *string `json:"hiddenAbil"`
	HiddenAbilDesc     *string `json:"hiddenAbilDesc"`
	SpecEventAbil      *string `json:"specEventAbil"`
	SpecEventAbilDesc  *string `json:"specEventAbilDesc"`
	MaleRatio          float64 `json:"maleRatio"`
	FemaleRatio        float64 `json:"femaleRatio"`
	BaseHappy          int     `json:"baseHappy"`
	GameOrigin         string  `json:"gameOrigin"`
	RegionOrigin       string  `json:"regionOrigin"`
	HealthStat         int     `json:"healthStat"`
	AttackStat         int     `json:"attackStat"`
	DefenseStat        int     `json:"defenseStat"`
	SpecialAttackStat  int     `json:"specialAttackStat"`
	SpecialDefenseStat int     `json:"specialDefenseStat"`
	SpeedStat          int     `json:"speedStat"`
	BaseStatTotal      int     `json:"baseStatTotal"`
	HealthEv           int     `json:"healthEV"`
	AttackEv           int     `json:"attackEV"`
	DefenseEv          int     `json:"defenseEV"`
	SpecialAttackEv    int     `json:"specialAttackEV"`
	SpecialDefenseEv   int     `json:"specialDefenseEV"`
	SpeedEv            int     `json:"speedEV"`
	EvYieldTotal       int     `json:"evYieldTotal"`
	CatchRate          int     `json:"catchRate"`
	ExpGrowth          string  `json:"expGrowth"`
	ExpGrowthTotal     int     `json:"expGrowthTotal"`
	ExpYield           int     `json:"expYield"`
	PrimEggGroup       string  `json:"primEggGroup"`
	SecEggGroup        string  `json:"secEggGroup"`
	EggCycle           int     `json:"eggCycle"`
	PreEvolutionID     *int    `json:"preEvolutionID"`
	EvolutionDetails   *string `json:"evolutionDetails"`
}
